// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKUAppAPI.Data;

namespace PKUAppAPI.Migrations
{
    [DbContext(typeof(PKUAppDbContext))]
    [Migration("20211022201150_v100")]
    partial class v100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "04552528-8283-4b70-9718-26721ccb8a31",
                            RoleId = "8923e08e-d84a-4d9c-aa85-7f45e356c0ec"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PKUAppAPI.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExerciseId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("PKUAppAPI.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MealId");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("PKUAppAPI.Models.MealProduct", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("MealId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("MealProducts");
                });

            modelBuilder.Entity("PKUAppAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carb")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phe")
                        .HasColumnType("int");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PKUAppAPI.Models.TrackedValue", b =>
                {
                    b.Property<int>("TrackedValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("TrackedValueId");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("TrackedValues");
                });

            modelBuilder.Entity("PKUAppAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "04552528-8283-4b70-9718-26721ccb8a31",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75ba8dd7-9b56-4f1b-8446-98e89d2d9c0c",
                            Email = "a@a",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "Admin",
                            NormalizedEmail = "A@A",
                            NormalizedUserName = "A@A",
                            PasswordHash = "AQAAAAEAACcQAAAAEBL4cOyqKAj9RrDhsSS8/d58jsvmIftRcR3+KEj4s5tBpDUrOPgNmzI2/o5lahLgoA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fe8f6f77-047b-4434-b39c-908a814caaf5",
                            TwoFactorEnabled = false,
                            UserName = "a@a"
                        },
                        new
                        {
                            Id = "9863e18f-4f1b-4471-b7c4-df3c3bbb014e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad0e2677-effc-4629-83e0-b27045122523",
                            Email = "u@u",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "User",
                            NormalizedEmail = "U@U",
                            NormalizedUserName = "U@U",
                            PasswordHash = "AQAAAAEAACcQAAAAED5Z2oF//G85jexywW6KOzoKYbSANSzWOHUNcFuXHZBL+lHcGoeawOaBB2Ym5F89XQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c97c27fe-209e-4cab-9c2e-2ff785137f71",
                            TwoFactorEnabled = false,
                            UserName = "u@u"
                        },
                        new
                        {
                            Id = "3cb24fec-9d0b-488a-8b06-e51deca24685",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00d323c4-6d5b-497c-b992-d26b50b259bb",
                            Email = "u@u2",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "User2",
                            NormalizedEmail = "U@U2",
                            NormalizedUserName = "U@U2",
                            PasswordHash = "AQAAAAEAACcQAAAAEIzP4qy+DDEgu8vLJ+kLBNzfSjyuBmmgxlmQC8nXhPpyIJ6Sn2fCj8x3jyKv6/8Lzw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1f1471ec-0793-499d-9d19-9ff679720b20",
                            TwoFactorEnabled = false,
                            UserName = "u@u2"
                        },
                        new
                        {
                            Id = "c2f2ba6f-c8d7-4dd8-83dd-02c3c213ce29",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b97e46d5-640b-4d1a-9530-a0aa00d853f9",
                            Email = "u@u3",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            Name = "User3",
                            NormalizedEmail = "U@U3",
                            NormalizedUserName = "U@U3",
                            PasswordHash = "AQAAAAEAACcQAAAAEAriJ/W6y6PSCkvkZ/SQ1mLbP0WYlY2UkgKxIAej58aquP+3m+XWedXAsCoEXEt6Rw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bc1468e9-7c6c-4a87-a778-4f0ca5a2696b",
                            TwoFactorEnabled = false,
                            UserName = "u@u3"
                        });
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserDailyLimits", b =>
                {
                    b.Property<int>("UserDailyLimitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AddCalories")
                        .HasColumnType("bit");

                    b.Property<int>("CaloriesLimit")
                        .HasColumnType("int");

                    b.Property<int>("CarbLimit")
                        .HasColumnType("int");

                    b.Property<int>("FatLimit")
                        .HasColumnType("int");

                    b.Property<int>("PheLimit")
                        .HasColumnType("int");

                    b.Property<int>("ProteinLimit")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserDailyLimitsId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("UserDailyLimits");

                    b.HasData(
                        new
                        {
                            UserDailyLimitsId = 1,
                            AddCalories = false,
                            CaloriesLimit = 0,
                            CarbLimit = 0,
                            FatLimit = 0,
                            PheLimit = 0,
                            ProteinLimit = 0,
                            UserId = "9863e18f-4f1b-4471-b7c4-df3c3bbb014e"
                        },
                        new
                        {
                            UserDailyLimitsId = 2,
                            AddCalories = false,
                            CaloriesLimit = 0,
                            CarbLimit = 0,
                            FatLimit = 0,
                            PheLimit = 0,
                            ProteinLimit = 0,
                            UserId = "3cb24fec-9d0b-488a-8b06-e51deca24685"
                        },
                        new
                        {
                            UserDailyLimitsId = 3,
                            AddCalories = false,
                            CaloriesLimit = 0,
                            CarbLimit = 0,
                            FatLimit = 0,
                            PheLimit = 0,
                            ProteinLimit = 0,
                            UserId = "c2f2ba6f-c8d7-4dd8-83dd-02c3c213ce29"
                        });
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserExercise", b =>
                {
                    b.Property<int>("UserExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("UserExercises");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserMedicine", b =>
                {
                    b.Property<int>("UserMedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carb")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fat")
                        .HasColumnType("int");

                    b.Property<int>("Phe")
                        .HasColumnType("int");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserMedicineId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMedicines");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserOffAlert", b =>
                {
                    b.Property<int>("UserOffAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserOffAlertId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOffAlerts");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserProductDish", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserProductDish");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserProductFav", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserProductFavs");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserProductLastAdded", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserProductLastAddeds");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PKUAppAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PKUAppAPI.Models.Meal", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.MealProduct", b =>
                {
                    b.HasOne("PKUAppAPI.Models.Meal", "Meal")
                        .WithMany("MealProducts")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PKUAppAPI.Models.Product", "Product")
                        .WithMany("MealProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PKUAppAPI.Models.Product", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.TrackedValue", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("TrackedValues")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserDailyLimits", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithOne("DailyLimits")
                        .HasForeignKey("PKUAppAPI.Models.UserDailyLimits", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserExercise", b =>
                {
                    b.HasOne("PKUAppAPI.Models.Exercise", "Exercise")
                        .WithMany("UserExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("UserExercises")
                        .HasForeignKey("UserId");

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserMedicine", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("UserMedicines")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserOffAlert", b =>
                {
                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("UserOffAlerts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserProductDish", b =>
                {
                    b.HasOne("PKUAppAPI.Models.Product", "Product")
                        .WithMany("UserProductDish")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("UserProductDish")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserProductFav", b =>
                {
                    b.HasOne("PKUAppAPI.Models.Product", "Product")
                        .WithMany("UserProductFavs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("UserProductFavs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.UserProductLastAdded", b =>
                {
                    b.HasOne("PKUAppAPI.Models.Product", "Product")
                        .WithMany("UserProductLastAddeds")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PKUAppAPI.Models.User", "User")
                        .WithMany("UserProductLastAddeds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PKUAppAPI.Models.Exercise", b =>
                {
                    b.Navigation("UserExercises");
                });

            modelBuilder.Entity("PKUAppAPI.Models.Meal", b =>
                {
                    b.Navigation("MealProducts");
                });

            modelBuilder.Entity("PKUAppAPI.Models.Product", b =>
                {
                    b.Navigation("MealProducts");

                    b.Navigation("UserProductDish");

                    b.Navigation("UserProductFavs");

                    b.Navigation("UserProductLastAddeds");
                });

            modelBuilder.Entity("PKUAppAPI.Models.User", b =>
                {
                    b.Navigation("DailyLimits");

                    b.Navigation("Meals");

                    b.Navigation("Products");

                    b.Navigation("TrackedValues");

                    b.Navigation("UserExercises");

                    b.Navigation("UserMedicines");

                    b.Navigation("UserOffAlerts");

                    b.Navigation("UserProductDish");

                    b.Navigation("UserProductFavs");

                    b.Navigation("UserProductLastAddeds");
                });
#pragma warning restore 612, 618
        }
    }
}
